### PR TITLE
Added import of a new option "notificationOptions"

### PR DESCRIPTION
**Pull request by alexmasita**
This is how I envision this option should be added in the `config/environment` under the already existing `esw-emberfire-messaging` as 
```
'esw-emberfire-messaging': {
      firebaseVersion: '4.2.0', // default (Firebase version used by SW)
      defaultBackgroundMessageTitle: 'New Message', // default (fallback title for background message),
      //However, am unsure why the notificationOptions below does not correctly merge into the 
      //notificationOptions object in the service worker.  Somehow, it is incorrectly merged in as a 
      //string [object object].  How can we solve this?
      notificationOptions: {
        //All supported notification options can be passed here
        vibrate: [200, 100, 200, 300]
      }
 }
```
Additionally, after studying the FCM documentation on the two message types, namely "Notification messages" and "Data messages" I realised it was necessary to merge-in the "data" key into the notificationOptions for two reasons:

1. To allow the use case of sending both the notification and data message types or
2. To only send the data message type which is necessary to be able customize the display notification from the service worker in the `setBackgroundMessageHandler`.

With this update, I believe for those who do not need advanced notification options, they can just add the `notificationOptions` key in `config/environment` and set it to an empty object and everything should continue to work as before.  

For those who want to pass additional `notificationOptions`, I believe they have to send a payload with the `data` key but WITHOUT the `notification` key so as to force the service worker to handle the payload instead of the FCM sdk handling it automatically.

Let me know your thoughts.

### CODE REVIEW

**Comment by Matt-Jensen** [comment]
Nice work on getting this done so quickly Alex!  I have a few things I'd like to address before we merge your work.

1. I'm seeing already merged code in your PR for some reason.  Do you know why?
2. I'm not sure about adding support for the non-standard [HTML5 notification option](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/showNotification) `timeOut`, which seems unique to a specific use case.  I'd prefer we encouraging users to fork this repo if they want to add features specific to this kind of requirement.
3. In reference to:

> shows => [object object] and is not merging in the object correctly. How can we parse it into an object correctly?

I think we may need to JSON.stringify the notification options in our build step and parse it in the service worker as the options are written to a configuration file.
3b. We should parse the notification options in the build step and warn the user of any invalid JSON (so we can fail fast).
4. The way the PR is using `Object.assign` is overwriting the individual notification configuration object.  The global notification configuration needs to be overwritten by the individual notification configuration instead.
5. I'd prefer we stick with the Firebase nomenclature of `notification` instead of `notificationOptions` to give users a sense of symmetry between our documentation.
6. Our build step should always write a global notification object to the SW settings file, regardless of whether a user provided one or not.

**Comment by alexmasita** [comment]
Hi Matt.

I agree with you on all your points.  To respond line by line:

The merged code you are seeing was a pull request I had initiated from my fork for the fastboot check which you had actually merged in your repo but I had apparently not merged into my fork as I opted to use your repo.  Does the merge mess the pull request?  Am still getting the hang of this pull request thing.

As for the time-out option, I have realized it is not even working for me at the moment and am unsure what to do to get it to work.  So I agree with you, let it be a subjective modification done at a users repo.  Though I wish there was a way we could easily override the service file for these sorts of modifications.

Agree with all your other points.  Perhaps you could give me a master class on your implementation of them? :).

For point 5. though, when you look at the online documentation, the second argument to `registration.showNotification(title, options)` is looked as an options object.  So am unclear whether keeping it as a notification object here could clearly show the translation from the notification object to the showNotification options object.  Either way, I am easy which way you choose to go with this.

**Comment by Matt-Jensen** [comment]
Ah that explains the duplicate code then.  Here's what I do for PR's, I clone the repo and create a new branch off of master `feature/all-notification-options` for example.  More than one way to do that, however that's what has worked for me.

> Agree with all your other points. Perhaps you could give me a master class on your implementation of them?

Sounds good to me. You pick the time next week (I'm on CST time) and we can screen share a PR of of the latest master.  Otherwise I can make a some commits to your PR next week when I have more flexibility.  I'll leave it up to you 😄

**Comment by alexmasita** [comment]
Super.  I get you.

What I normally do that I find faster is modify the installed add-on code while my app is running and see that my new code runs with the modification.  I then fork the repo of the add-on from author and copy over the modified code from my app to the fork's master and then issue a pull request from there.

I think what would be more efficient is, you make some commits to my PR then I can examine your implementation.  If I find I can't get my head around some of them, then we can have live share.  Thanks Matt.

**Comment by Matt-Jensen** [comment]
closed by #8

**Pull request closed without merging**
